name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.8-eclipse-temurin-8
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile and Package
        run: |
          mvn compile
          mvn package
    outputs:
      build-dir: target

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.8-eclipse-temurin-8
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.8-eclipse-temurin-8
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find JAR file
        run: ls ./target/*.jar || echo "No JAR file found!"